name: Make docs

on: [push]

jobs:
  make_docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Doxygen Action
        uses: mattnotmitt/doxygen-action@v1.1.0
        with:
          doxyfile-path: ./Doxyfile
          working-directory: .

      - uses: EndBug/add-and-commit@v4
        with:
          author_name: Docs Robot
          author_email: robot@example.com
          message: "Committing documentation changes"
